//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loverSitios
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idUsuario { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> identificacion { get; set; }
        public Nullable<int> tipoIdentificacion { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string clave { get; set; }
        public Nullable<bool> Reestablecer { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual rol rol { get; set; }
        public virtual tipoIdentificacion tipoIdentificacion1 { get; set; }
    }
}
