//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionGestorIndicadores
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public int idMensaje { get; set; }
        public Nullable<int> idTexto1 { get; set; }
        public Nullable<int> idTexto2 { get; set; }
    
        public virtual texto texto { get; set; }
        public virtual texto texto1 { get; set; }
    }
}
