//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionGestorIndicadores
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModEmparejamiento
    {
        public Nullable<int> CriterioInteres { get; set; }
        public Nullable<bool> EdadCriterio { get; set; }
        public Nullable<bool> TestCriterio { get; set; }
        public int Id_modconf { get; set; }
    }
}
