//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loverSitios.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiusr3pl_loverEntities1 : DbContext
    {
        public tiusr3pl_loverEntities1()
            : base("name=tiusr3pl_loverEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria_interes> categoria_interes { get; set; }
        public virtual DbSet<categoria_preferencia> categoria_preferencia { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<foto> foto { get; set; }
        public virtual DbSet<generoCliente> generoCliente { get; set; }
        public virtual DbSet<interes> interes { get; set; }
        public virtual DbSet<interes_ciente> interes_ciente { get; set; }
        public virtual DbSet<match1> match1 { get; set; }
        public virtual DbSet<match2> match2 { get; set; }
        public virtual DbSet<mensaje> mensaje { get; set; }
        public virtual DbSet<ModEmparejamiento> ModEmparejamiento { get; set; }
        public virtual DbSet<preferencia> preferencia { get; set; }
        public virtual DbSet<preferencia_cliente> preferencia_cliente { get; set; }
        public virtual DbSet<preguntaTest> preguntaTest { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<suspiro1> suspiro1 { get; set; }
        public virtual DbSet<suspiro2> suspiro2 { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<testUser> testUser { get; set; }
        public virtual DbSet<texto> texto { get; set; }
        public virtual DbSet<tipo_genero> tipo_genero { get; set; }
        public virtual DbSet<tipoIdentificacion> tipoIdentificacion { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<ConfCorreos> ConfCorreos { get; set; }
        public virtual DbSet<Correos> Correos { get; set; }
    }
}
