//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loverSitios.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestaTest
    {
        public int id_respuestaTest { get; set; }
        public Nullable<int> idPregunta { get; set; }
        public string respuesta { get; set; }
    
        public virtual preguntaTest preguntaTest { get; set; }
    }
}
