//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaPresentacionValidadorPerfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class generoCliente
    {
        public int idGenero { get; set; }
        public Nullable<int> idtipoGenero { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipo_genero tipo_genero { get; set; }
    }
}
