//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaPresentacionCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public int idUbicación { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string latitud { get; set; }
        public string logitud { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
